var rule = {
  title: '',
  //host: 'https://thep5045.cc/',
  host: 'https://thepthep2104.cc/',
hostJs:'print(HOST);let html=request(HOST,{headers:{"User-Agent":PC_UA}});HOST = jsp.pdfh(html,".show_hosta:eq(0)&&href");log(HOST);',
  url: '/fyfilter',
  filterable: 1, //是否启用分类筛选
  filter_url: '{{fl.cateId}}/fypage',
  filter: {
    "categories/all": [{
      "key": "cateId",
      "name": "分类",
      "value": [
       {"n": "全部", "v": ""},
        {"v": "categories/wife", "n": "人妻"},
        {"v": "categories/big_tits", "n": "巨乳"},
        {"v": "categories/anal", "n": "肛交"},
        {"v": "categories/MILF", "n": "熟女"},
        {"v": "categories/teen", "n": "少女"},
        {"v": "categories/young_woman", "n": "少妇"},
        {"v": "categories/uniform", "n": "制服"},
        {"v": "categories/student", "n": "学生"},
        {"v": "categories/female_teacher", "n": "女教师"},
        {"v": "categories/long_legs", "n": "长腿"},
        {"v": "categories/cosplay", "n": "角色扮演"},
        {"v": "categories/footjob", "n": "足交"},
        {"v": "categories/oral_sex", "n": "口交"},
        {"v": "categories/group_sex", "n": "群P"},
        {"v": "categories/facial", "n": "颜射"},
        {"v": "categories/masturbation", "n": "自慰"},
        {"v": "categories/rape", "n": "强奸"},
        {"v": "categories/kiss", "n": "接吻"},
        {"v": "categories/virgin", "n": "处女"},
        {"v": "categories/sm", "n": "SM"},
        {"v": "categories/massage", "n": "按摩"},
        {"v": "categories/creampie", "n": "中出"},
        {"v": "categories/nurse", "n": "护士"},
        {"v": "categories/lesbian", "n": "女同"},
        {"v": "categories/office", "n": "办公室"},
        {"v": "categories/squirting", "n": "潮吹"},
        {"v": "categories/ebony", "n": "黑人"},
        {"v": "categories/amateur", "n": "自拍"},
        {"v": "categories/chinese", "n": "中国"},
        {"v": "categories/eu", "n": "欧美"},
        {"v": "categories/japan", "n": "日本"},
        {"v": "categories/south_korean", "n": "韩国"},
        {"v": "categories/russian", "n": "俄罗斯"},
        {"v": "categories/india", "n": "印度"},
        {"v": "categories/thailand", "n": "泰国"},
        {"v": "categories/taiwan", "n": "台湾"},
        {"v": "categories/hongkong", "n": "香港"},
        {"v": "categories/eu", "n": "欧美"}
      ]
    }]
  },
  filter_def: {
    'categories/all': {cateId: 'categories/all'},
    'jav/uncensored': {cateId: 'jav/uncensored'},
    1: {cateId: '1'},
    3: {cateId: '3'},
    4: {cateId: '4'}  // 移除了末尾多余逗号
  },
  searchUrl: '/search/**/fypage?',
  searchable: 2,
  quickSearch: 0,
  headers: {
    'User-Agent': 'MOBILE_UA'
  },
  class_name: '全部影片&日本无码&欧美&人妻&肛交&熟女&少妇&口交&群交&自慰&黑人&中国&香港',
  tab_remove: '失效',
  class_url: 'categories/all&jav/uncensored&eu&categories/wife&categories/anal&categories/MILF&categories/young_woman&categories/oral_sex&categories/group_sex&categories/masturbation&categories/ebony&categories/chinese&categories/hongkong',
  limit: 6,
  double: true,
  推荐: '.index-container .video-av-data;.avdata.card;img&&alt;img&&data-src;.duration&&Text;a&&href',
  一级: '.video-list .avdata;img&&alt;img&&data-src;.duration&&Text;.av-link&&href',
  二级: '*',
  搜索: '*'  // 移除了末尾多余逗号
};
